<a href="https://colab.research.google.com/github/freddy-7/TI2001B-2023/blob/main/1_Extracci%C3%B3n_Datos.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#INSTALAR LIBRERIAS
!pip install pandas
!pip install numpy
!pip install matplotlib
!pip install seaborn
!pip install openpyxl

Requirement already satisfied: pandas in c:\users\cervantes\appdata\local\programs\python\python312\lib\site-packages (2.2.3)
Requirement already satisfied: numpy>=1.26.0 in c:\users\cervantes\appdata\local\programs\python\python312\lib\site-packages (from pandas) (1.26.3)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\cervantes\appdata\local\programs\python\python312\lib\site-packages (from pandas) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in c:\users\cervantes\appdata\local\programs\python\python312\lib\site-packages (from pandas) (2024.2)
Requirement already satisfied: tzdata>=2022.7 in c:\users\cervantes\appdata\local\programs\python\python312\lib\site-packages (from pandas) (2024.2)
Requirement already satisfied: six>=1.5 in c:\users\cervantes\appdata\local\programs\python\python312\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.16.0)

[notice] A new release of pip is available: 23.3.2 -> 25.2
[notice] To update, run: python.exe -m pip install --upgrade pip

Requirement already satisfied: numpy in c:\users\cervantes\appdata\local\programs\python\python312\lib\site-packages (1.26.3)

[notice] A new release of pip is available: 23.3.2 -> 25.2
[notice] To update, run: python.exe -m pip install --upgrade pip

Requirement already satisfied: matplotlib in c:\users\cervantes\appdata\local\programs\python\python312\lib\site-packages (3.8.2)
Requirement already satisfied: contourpy>=1.0.1 in c:\users\cervantes\appdata\local\programs\python\python312\lib\site-packages (from matplotlib) (1.2.0)
Requirement already satisfied: cycler>=0.10 in c:\users\cervantes\appdata\local\programs\python\python312\lib\site-packages (from matplotlib) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in c:\users\cervantes\appdata\local\programs\python\python312\lib\site-packages (from matplotlib) (4.47.2)
Requirement already satisfied: kiwisolver>=1.3.1 in c:\users\cervantes\appdata\local\programs\python\python312\lib\site-packages (from matplotlib) (1.4.5)
Requirement already satisfied: numpy<2,>=1.21 in c:\users\cervantes\appdata\local\programs\python\python312\lib\site-packages (from matplotlib) (1.26.3)
Requirement already satisfied: packaging>=20.0 in c:\users\cervantes\appdata\local\programs\python\python312\lib\site-packages (from matplotlib) (23.2)
Requirement already satisfied: pillow>=8 in c:\users\cervantes\appdata\local\programs\python\python312\lib\site-packages (from matplotlib) (10.2.0)
Requirement already satisfied: pyparsing>=2.3.1 in c:\users\cervantes\appdata\local\programs\python\python312\lib\site-packages (from matplotlib) (3.1.1)
Requirement already satisfied: python-dateutil>=2.7 in c:\users\cervantes\appdata\local\programs\python\python312\lib\site-packages (from matplotlib) (2.8.2)
Requirement already satisfied: six>=1.5 in c:\users\cervantes\appdata\local\programs\python\python312\lib\site-packages (from python-dateutil>=2.7->matplotlib) (1.16.0)

[notice] A new release of pip is available: 23.3.2 -> 25.2
[notice] To update, run: python.exe -m pip install --upgrade pip

Requirement already satisfied: seaborn in c:\users\cervantes\appdata\local\programs\python\python312\lib\site-packages (0.13.2)
Requirement already satisfied: numpy!=1.24.0,>=1.20 in c:\users\cervantes\appdata\local\programs\python\python312\lib\site-packages (from seaborn) (1.26.3)
Requirement already satisfied: pandas>=1.2 in c:\users\cervantes\appdata\local\programs\python\python312\lib\site-packages (from seaborn) (2.2.3)
Requirement already satisfied: matplotlib!=3.6.1,>=3.4 in c:\users\cervantes\appdata\local\programs\python\python312\lib\site-packages (from seaborn) (3.8.2)
Requirement already satisfied: contourpy>=1.0.1 in c:\users\cervantes\appdata\local\programs\python\python312\lib\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (1.2.0)
Requirement already satisfied: cycler>=0.10 in c:\users\cervantes\appdata\local\programs\python\python312\lib\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in c:\users\cervantes\appdata\local\programs\python\python312\lib\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (4.47.2)
Requirement already satisfied: kiwisolver>=1.3.1 in c:\users\cervantes\appdata\local\programs\python\python312\lib\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (1.4.5)
Requirement already satisfied: packaging>=20.0 in c:\users\cervantes\appdata\local\programs\python\python312\lib\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (23.2)
Requirement already satisfied: pillow>=8 in c:\users\cervantes\appdata\local\programs\python\python312\lib\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (10.2.0)
Requirement already satisfied: pyparsing>=2.3.1 in c:\users\cervantes\appdata\local\programs\python\python312\lib\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (3.1.1)
Requirement already satisfied: python-dateutil>=2.7 in c:\users\cervantes\appdata\local\programs\python\python312\lib\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in c:\users\cervantes\appdata\local\programs\python\python312\lib\site-packages (from pandas>=1.2->seaborn) (2024.2)
Requirement already satisfied: tzdata>=2022.7 in c:\users\cervantes\appdata\local\programs\python\python312\lib\site-packages (from pandas>=1.2->seaborn) (2024.2)
Requirement already satisfied: six>=1.5 in c:\users\cervantes\appdata\local\programs\python\python312\lib\site-packages (from python-dateutil>=2.7->matplotlib!=3.6.1,>=3.4->seaborn) (1.16.0)

[notice] A new release of pip is available: 23.3.2 -> 25.2
[notice] To update, run: python.exe -m pip install --upgrade pip

Requirement already satisfied: openpyxl in c:\users\cervantes\appdata\local\programs\python\python312\lib\site-packages (3.1.5)
Requirement already satisfied: et-xmlfile in c:\users\cervantes\appdata\local\programs\python\python312\lib\site-packages (from openpyxl) (2.0.0)

[notice] A new release of pip is available: 23.3.2 -> 25.2
[notice] To update, run: python.exe -m pip install --upgrade pip

In [3]:
#Importamos librer√≠as requeridas
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [ ]:
#GOOGLE COLAB
#Cargar archivo csv desde equipo
from google.colab import files
files.upload()

CARGA DE ARCHIVO .CSV

In [ ]:
#Convertir en dataframe
df_csv= pd.read_csv("Datos de Facturacion.excel")
df_csv

CARGA DE ARCHIVO XLSX

In [4]:
#Carga desde un archivo .xlsx sin indice
df= pd.read_excel('Datos de Facturaci√≥n.xlsx')
df

,CVE_DOC,CVE_CLPV,STATUS,CVE_VEND,FECHAELAB,FECHA_DOC,FECHA_ENT,FECHA_VEN,FECHA_CANCELA,CAN_TOT,DES_TOT,DES_FIN
0,F29414,2465,C,1.0,2019-09-03 08:58:42.000,2019-09-03,2019-09-03 00:00:00,2019-09-18,2019-09-04,3980.00,0.0,0.0
1,F29415,3926,C,1.0,2019-09-03 09:55:14.000,2019-09-03,2019-09-03 00:00:00,2019-10-03,2019-09-03,1550.00,0.0,0.0
2,F29416,3926,C,1.0,2019-09-03 13:25:33.000,2019-09-03,2019-09-03 00:00:00,2019-10-03,2019-09-03,1550.00,0.0,0.0
3,F29417,3926,C,1.0,2019-09-03 13:33:23.000,2019-09-03,2019-09-03 00:00:00,2019-10-03,2019-09-17,1550.00,0.0,0.0
4,F29418,6813,C,2.0,2019-09-03 14:23:45.000,2019-09-03,2019-09-03 00:00:00,2019-09-03,2019-09-10,2435.44,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...
10890,F40306,8842,E,2.0,2023-03-06 16:09:39.013,2023-03-06,2023-03-01 00:00:00,2023-03-06,NaT,3272.00,0.0,0.0
10891,F40307,6218,NaN,2.0,2023-03-06 16:38:42.933,2023-03-06,2023-03-06 00:00:00,2023-03-06,NaT,504.15,0.0,0.0
10892,NaN,5926,E,2.0,2023-03-06 17:02:33.390,2023-03-06,2023-03-06 00:00:00,2023-03-06,NaT,275.68,0.0,0.0
10893,F40309,361,E,2.0,2023-03-07 12:43:49.567,2023-03-07,2023-03-07 00:00:00,2023-03-07,NaT,129.30,0.0,0.0
10894,F40310,3011,E,2.0,2023-03-07 12:45:58.407,2023-03-07,2023-03-01 00:00:00,2023-03-07,NaT,517.20,0.0,0.0

In [13]:
#Verificamos informaci√≥n del DataFrame
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10895 entries, 0 to 10894
Data columns (total 12 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   CVE_DOC        10890 non-null  object
 1   CVE_CLPV       10830 non-null  float64
 2   STATUS         10886 non-null  object
 3   CVE_VEND       10847 non-null  float64
 4   FECHAELAB      10893 non-null  datetime64[ns]
 5   FECHA_DOC      10894 non-null  datetime64[ns]
 6   FECHA_ENT      10893 non-null  object
 7   FECHA_VEN      10895 non-null  datetime64[ns]
 8   FECHA_CANCELA  358 non-null    datetime64[ns]
 9   CAN_TOT        10889 non-null  float64
 10  DES_TOT        10894 non-null  float64
 11  DES_FIN        10892 non-null  float64
dtypes: datetime64[ns](4), float64(5), object(3)
memory usage: 1021.5+ KB

In [36]:
#Imprimo los primeros 5 registro del dataframe
df.head()

,CVE_DOC,CVE_CLPV,STATUS,CVE_VEND,FECHAELAB,FECHA_DOC,FECHA_ENT,FECHA_VEN,FECHA_CANCELA,CAN_TOT,DES_TOT,DES_FIN
0,F29414,2465.0,C,1.0,2019-09-03 08:58:42,2019-09-03,2019-09-03,2019-09-18,2019-09-04,3980.00,0.0,0.0
1,F29415,3926.0,C,1.0,2019-09-03 09:55:14,2019-09-03,2019-09-03,2019-10-03,2019-09-03,1550.00,0.0,0.0
2,F29416,3926.0,C,1.0,2019-09-03 13:25:33,2019-09-03,2019-09-03,2019-10-03,2019-09-03,1550.00,0.0,0.0
3,F29417,3926.0,C,1.0,2019-09-03 13:33:23,2019-09-03,2019-09-03,2019-10-03,2019-09-17,1550.00,0.0,0.0
4,F29418,6813.0,C,2.0,2019-09-03 14:23:45,2019-09-03,2019-09-03,2019-09-03,2019-09-10,2435.44,0.0,0.0

**FILTROS BASICOS PARA VARIABLES CUALITATIVAS**

In [35]:
#Filtro por objeto
filtro1=df[df["NOMBRE"] == "INDUSTRIAS LANCERMEX"]
filtro1

KeyError: 'NOMBRE'

In [33]:
#Filtro por filas
filtro2= df.iloc[7001:7100,: ]           #Filas consecutivas
#filtro2=df.iloc[ [8, 24, 100] , : ]  #Filas no consecutivas
filtro2

,CVE_DOC,CVE_CLPV,STATUS,CVE_VEND,FECHAELAB,FECHA_DOC,FECHA_ENT,FECHA_VEN,FECHA_CANCELA,CAN_TOT,DES_TOT,DES_FIN
7001,F36417,5271.0,E,3.0,2021-10-15 08:40:29.183,2021-10-15,2021-10-06,2021-11-14,NaT,8555.24,0.0,0.0
7002,F36418,5746.0,E,2.0,2021-10-15 08:51:03.463,2021-10-15,2021-10-14,2021-10-15,NaT,620.77,0.0,0.0
7003,F36419,2163.0,E,3.0,2021-10-15 08:56:23.280,2021-10-15,2021-10-15,2021-10-15,NaT,560.00,0.0,0.0
7004,F36420,1429.0,E,1.0,2021-10-15 09:01:08.393,2021-10-15,2021-10-15,2021-12-14,NaT,23625.00,0.0,0.0
7005,F36421,5039.0,E,1.0,2021-10-15 09:07:07.103,2021-10-15,2021-10-08,2022-01-13,NaT,3308.78,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...
7095,F36511,4480.0,E,2.0,2021-10-27 13:07:43.223,2021-10-27,2021-10-27,2021-11-11,NaT,1137.50,0.0,0.0
7096,F36512,8186.0,E,2.0,2021-10-27 13:22:23.980,2021-10-27,2021-10-27,2021-10-27,NaT,94.84,0.0,0.0
7097,F36513,4403.0,E,2.0,2021-10-27 13:35:40.677,2021-10-27,2021-10-27,2021-10-27,NaT,847.00,0.0,0.0
7098,F36514,5589.0,E,2.0,2021-10-27 14:02:54.630,2021-10-27,2021-10-27,2021-10-27,NaT,965.00,0.0,0.0
7099,F36515,5589.0,E,2.0,2021-10-27 14:04:26.797,2021-10-27,2021-10-26,2021-10-27,NaT,2106.00,0.0,0.0

In [30]:
#Filtro por columnas
#filtro3=df.iloc[ : , 0:3]       #Columnas consecutivas
filtro3=df.iloc[ : , [0,6,7,9]]  #Columnas no consecutivas
filtro3

      CVE_DOC  FECHA_ENT  FECHA_VEN  CAN_TOT
0      F29414 2019-09-03 2019-09-18  3980.00
1      F29415 2019-09-03 2019-10-03  1550.00
2      F29416 2019-09-03 2019-10-03  1550.00
3      F29417 2019-09-03 2019-10-03  1550.00
4      F29418 2019-09-03 2019-09-03  2435.44
...       ...        ...        ...      ...
10890  F40306 2023-03-01 2023-03-06  3272.00
10891  F40307 2023-03-06 2023-03-06   504.15
10892     NaN 2023-03-06 2023-03-06   275.68
10893  F40309 2023-03-07 2023-03-07   129.30
10894  F40310 2023-03-01 2023-03-07   517.20

[10895 rows x 4 columns]

In [ ]:
#GOOGLE COLAB
#Filtro de filas vs columnas
#Paso 1: Leemos el contenido del archivo
from google.colab import files
uploaded=files.upload()

In [44]:
df1= pd.read_excel('Datos de Facturaci√≥n.xlsx', index_col=1)
df1

,CVE_DOC,STATUS,CVE_VEND,FECHAELAB,FECHA_DOC,FECHA_ENT,FECHA_VEN,FECHA_CANCELA,CAN_TOT,DES_TOT,DES_FIN
CVE_CLPV,,,,,,,,,,,
2465,F29414,C,1.0,2019-09-03 08:58:42.000,2019-09-03,2019-09-03 00:00:00,2019-09-18,2019-09-04,3980.00,0.0,0.0
3926,F29415,C,1.0,2019-09-03 09:55:14.000,2019-09-03,2019-09-03 00:00:00,2019-10-03,2019-09-03,1550.00,0.0,0.0
3926,F29416,C,1.0,2019-09-03 13:25:33.000,2019-09-03,2019-09-03 00:00:00,2019-10-03,2019-09-03,1550.00,0.0,0.0
3926,F29417,C,1.0,2019-09-03 13:33:23.000,2019-09-03,2019-09-03 00:00:00,2019-10-03,2019-09-17,1550.00,0.0,0.0
6813,F29418,C,2.0,2019-09-03 14:23:45.000,2019-09-03,2019-09-03 00:00:00,2019-09-03,2019-09-10,2435.44,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...
8842,F40306,E,2.0,2023-03-06 16:09:39.013,2023-03-06,2023-03-01 00:00:00,2023-03-06,NaT,3272.00,0.0,0.0
6218,F40307,NaN,2.0,2023-03-06 16:38:42.933,2023-03-06,2023-03-06 00:00:00,2023-03-06,NaT,504.15,0.0,0.0
5926,NaN,E,2.0,2023-03-06 17:02:33.390,2023-03-06,2023-03-06 00:00:00,2023-03-06,NaT,275.68,0.0,0.0
361,F40309,E,2.0,2023-03-07 12:43:49.567,2023-03-07,2023-03-07 00:00:00,2023-03-07,NaT,129.30,0.0,0.0
3011,F40310,E,2.0,2023-03-07 12:45:58.407,2023-03-07,2023-03-01 00:00:00,2023-03-07,NaT,517.20,0.0,0.0

In [ ]:
#Paso 2: Aplicamos Filtro de filas vs columnas
filtro4=df1.loc[["HELVEX","DONGA HWASUNG MEXICO"], ["MONTO ADEUDADO"]]
filtro4

In [ ]:
#Filtro por cabecera
filtro5=df.head(10)
filtro5

**FILTROS BASICOS PARA VARIABLES CUANTITATIVAS**

In [22]:
#Filtro por comparacion
df['FECHA_ENT'] = pd.to_datetime(df['FECHA_ENT'], errors='coerce')
#filtro6=df[df["FECHA_ENT"] == '28/02/2022 00:00']
filtro6 = df[df['FECHA_ENT'].dt.date == pd.to_datetime('28/02/2022').date()]
filtro6

C:\Users\Cervantes\AppData\Local\Temp\ipykernel_10860\4219448860.py:4: UserWarning: Parsing dates in %d/%m/%Y format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.
  filtro6 = df[df['FECHA_ENT'].dt.date == pd.to_datetime('28/02/2022').date()]

,CVE_DOC,CVE_CLPV,STATUS,CVE_VEND,FECHAELAB,FECHA_DOC,FECHA_ENT,FECHA_VEN,FECHA_CANCELA,CAN_TOT,DES_TOT,DES_FIN
8077,F37493,4598.0,E,1.0,2022-02-28 10:56:02.460,2022-02-28,2022-02-28,2022-03-30,NaT,44259.0000,0.0,0.0
8078,F37494,1943.0,C,2.0,2022-02-28 11:34:00.367,2022-02-28,2022-02-28,2022-02-28,2022-02-28,89.6800,0.0,0.0
8081,F37497,1943.0,C,2.0,2022-02-28 12:05:42.377,2022-02-28,2022-02-28,2022-02-28,2022-02-28,89.6800,0.0,0.0
8083,F37499,8573.0,E,2.0,2022-02-28 12:25:29.833,2022-02-28,2022-02-28,2022-02-28,NaT,997.5400,0.0,0.0
8084,F37500,8249.0,E,2.0,2022-02-28 12:32:46.687,2022-02-28,2022-02-28,2022-02-28,NaT,2508.7000,0.0,0.0
8090,F37506,1757.0,E,2.0,2022-02-28 13:23:45.440,2022-02-28,2022-02-28,2022-02-28,NaT,2586.2100,0.0,0.0
8091,F37507,3108.0,E,2.0,2022-02-28 13:52:43.383,2022-02-28,2022-02-28,2022-02-28,NaT,675.4000,0.0,0.0
8092,F37508,6232.0,E,2.0,2022-02-28 14:46:56.940,2022-02-28,2022-02-28,2022-02-28,NaT,941.3965,0.0,0.0
8095,F37511,8593.0,E,2.0,2022-02-28 15:20:58.040,2022-02-28,2022-02-28,2022-02-28,NaT,218.9700,0.0,0.0
8096,F37512,4766.0,E,2.0,2022-02-28 15:54:16.277,2022-02-28,2022-02-28,2022-02-28,NaT,9450.0000,0.0,0.0
8100,F37516,6179.0,E,3.0,2022-02-28 16:33:54.413,2022-02-28,2022-02-28,2022-02-28,NaT,5951.7000,0.0,0.0
8103,F37519,5150.0,E,3.0,2022-02-28 17:09:39.213,2022-02-28,2022-02-28,2022-02-28,NaT,2040.0000,0.0,0.0
8104,F37520,4527.0,E,2.0,2022-02-28 17:14:57.487,2022-02-28,2022-02-28,2022-02-28,NaT,4315.0000,0.0,0.0
8107,F37523,5926.0,E,2.0,2022-02-28 17:36:54.363,2022-02-28,2022-02-28,2022-02-28,NaT,451.6100,0.0,0.0
8133,F37549,3016.0,E,1.0,2022-03-04 15:08:49.747,2022-03-04,2022-02-28,2022-03-04,NaT,1083.7200,0.0,0.0
8148,F37564,4695.0,E,1.0,2022-03-08 09:15:20.507,2022-03-08,2022-02-28,2022-05-07,NaT,5515.0000,0.0,0.0
8204,F37620,8316.0,E,3.0,2022-03-14 17:00:43.247,2022-03-14,2022-02-28,2022-03-14,NaT,24570.3000,0.0,0.0

**FILTROS BASICOS CON CONETORES LOGICOS**

In [ ]:
#Filtro Y
#df['CVE_CLPV'] = pd.to_numeric(df['CVE_CLPV'], errors='coerce')
#filtro7 = df[(df['CVE_VEND'] != 5) & (df['CVE_VEND'] != 4)] #utilizando el operador ! diferente de
#filtro7
# Paso 1: Filtra el DataFrame para las filas con CVE_VEND 1 o 2
df_filtrado = df[df['CVE_VEND'].isin([1, 2])]
filtro7 = df_filtrado.set_index('CVE_VEND')

filtro7

,CVE_DOC,CVE_CLPV,STATUS,FECHAELAB,FECHA_DOC,FECHA_ENT,FECHA_VEN,FECHA_CANCELA,CAN_TOT,DES_TOT,DES_FIN
CVE_VEND,,,,,,,,,,,
1.0,F29414,2465.0,C,2019-09-03 08:58:42.000,2019-09-03,2019-09-03,2019-09-18,2019-09-04,3980.00,0.0,0.0
1.0,F29415,3926.0,C,2019-09-03 09:55:14.000,2019-09-03,2019-09-03,2019-10-03,2019-09-03,1550.00,0.0,0.0
1.0,F29416,3926.0,C,2019-09-03 13:25:33.000,2019-09-03,2019-09-03,2019-10-03,2019-09-03,1550.00,0.0,0.0
1.0,F29417,3926.0,C,2019-09-03 13:33:23.000,2019-09-03,2019-09-03,2019-10-03,2019-09-17,1550.00,0.0,0.0
2.0,F29418,6813.0,C,2019-09-03 14:23:45.000,2019-09-03,2019-09-03,2019-09-03,2019-09-10,2435.44,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...
2.0,F40306,8842.0,E,2023-03-06 16:09:39.013,2023-03-06,2023-03-01,2023-03-06,NaT,3272.00,0.0,0.0
2.0,F40307,6218.0,NaN,2023-03-06 16:38:42.933,2023-03-06,2023-03-06,2023-03-06,NaT,504.15,0.0,0.0
2.0,NaN,5926.0,E,2023-03-06 17:02:33.390,2023-03-06,2023-03-06,2023-03-06,NaT,275.68,0.0,0.0
2.0,F40309,361.0,E,2023-03-07 12:43:49.567,2023-03-07,2023-03-07,2023-03-07,NaT,129.30,0.0,0.0
2.0,F40310,3011.0,E,2023-03-07 12:45:58.407,2023-03-07,2023-03-01,2023-03-07,NaT,517.20,0.0,0.0

In [24]:
#Filtro o
filtro8=df[(df["CAN_TOT"] < 5951.7) | (df["STATUS"] == "E")]
filtro8

,CVE_DOC,CVE_CLPV,STATUS,CVE_VEND,FECHAELAB,FECHA_DOC,FECHA_ENT,FECHA_VEN,FECHA_CANCELA,CAN_TOT,DES_TOT,DES_FIN
0,F29414,2465.0,C,1.0,2019-09-03 08:58:42.000,2019-09-03,2019-09-03,2019-09-18,2019-09-04,3980.00,0.0,0.0
1,F29415,3926.0,C,1.0,2019-09-03 09:55:14.000,2019-09-03,2019-09-03,2019-10-03,2019-09-03,1550.00,0.0,0.0
2,F29416,3926.0,C,1.0,2019-09-03 13:25:33.000,2019-09-03,2019-09-03,2019-10-03,2019-09-03,1550.00,0.0,0.0
3,F29417,3926.0,C,1.0,2019-09-03 13:33:23.000,2019-09-03,2019-09-03,2019-10-03,2019-09-17,1550.00,0.0,0.0
4,F29418,6813.0,C,2.0,2019-09-03 14:23:45.000,2019-09-03,2019-09-03,2019-09-03,2019-09-10,2435.44,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...
10890,F40306,8842.0,E,2.0,2023-03-06 16:09:39.013,2023-03-06,2023-03-01,2023-03-06,NaT,3272.00,0.0,0.0
10891,F40307,6218.0,NaN,2.0,2023-03-06 16:38:42.933,2023-03-06,2023-03-06,2023-03-06,NaT,504.15,0.0,0.0
10892,NaN,5926.0,E,2.0,2023-03-06 17:02:33.390,2023-03-06,2023-03-06,2023-03-06,NaT,275.68,0.0,0.0
10893,F40309,361.0,E,2.0,2023-03-07 12:43:49.567,2023-03-07,2023-03-07,2023-03-07,NaT,129.30,0.0,0.0
10894,F40310,3011.0,E,2.0,2023-03-07 12:45:58.407,2023-03-07,2023-03-01,2023-03-07,NaT,517.20,0.0,0.0

In [ ]:
#Filtro not
filtro9=df[~(df["MONTO ADEUDADO"] >= 6000)]
filtro9

In [46]:
#Convertir archivo filtrado a CSV
filtro7.to_csv("7-Index= CVE_VEND.csv")

In [ ]:
#GOOGLE COLAB
#descardar archivo filtrado en csv
from google.colab import files


files.download("Entregable1.csv")